version: "3"

services:
  https-portal:
    image: steveltn/https-portal:1
    container_name: misskey-https-portal
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: 'misskey.tebukuro.xyz -> http://host.docker.internal:3000'
      STAGE: 'production'
      WEBSOCKET: 'true'
      # FORCE_RENEW: 'true'
    volumes:
      - https-portal-data:/var/lib/https-portal

volumes:
    https-portal-data:
